# File: netlify.toml

[build]
  # Beritahu Netlify bahwa file publik kita ada di folder "dist".
  # Ini adalah pengaturan yang paling penting.
  publish = "dist"

  # Folder tempat Anda menyimpan file function .js Anda.
  functions = "netlify/functions"

# Redirects rule untuk Single Page Application (PENTING!)
# Agar halaman tidak error 404 saat di-refresh.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200