# File: netlify.toml

[build]
  # --- INI BAGIAN YANG ANDA GANTI ---
  # Perintah ini akan membangun frontend Anda menjadi file statis di folder "dist".
  command = "npm run build"
  
  publish = "dist"
  functions = "netlify/functions"

# --- BAGIAN DI BAWAH INI SUDAH SEMPURNA, JANGAN DIUBAH ---
# PERBAIKAN TIMEOUT v2.0: Hanya untuk "Otak" AI kita
[functions."generate"]
  timeout = 60 # Menaikkan stopwatch HANYA untuk generate.js
# --- AKHIR PERBAIKAN ---

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200